SELECT 
SK_ID_PREV, 
SK_ID_CURR, 
NAME_CONTRACT_TYPE, 
AMT_ANNUITY, 
AMT_APPLICATION, 
AMT_CREDIT, 
AMT_GOODS_PRICE, 
WEEKDAY_APPR_PROCESS_START, 
HOUR_APPR_PROCESS_START, 
FLAG_LAST_APPL_PER_CONTRACT, 
NFLAG_LAST_APPL_IN_DAY
FROM previous_application
WHERE AMT_ANNUITY IS NOT NULL AND AMT_GOODS_PRICE IS NOT NULL


