---SELECT  
--SK_ID_CURR, SK_ID_BUREAU, DAYS_CREDIT,
--CREDIT_DAY_OVERDUE, DAYS_CREDIT_ENDDATE, DAYS_ENDDATE_FACT, 
--AMT_CREDIT_MAX_OVERDUE, CNT_CREDIT_PROLONG, AMT_CREDIT_SUM, 
--AMT_CREDIT_SUM_DEBT, AMT_CREDIT_SUM_LIMIT, AMT_CREDIT_SUM_OVERDUE, DAYS_CREDIT_UPDATE

--FROM bureau
--GROUP BY DAYS_CREDIT
--LIMIT 10


SELECT * FROM bureau_balance