SELECT 
COUNT(CREDIT_ACTIVE) AS CONTAS_ATIVAS,  
(DAYS_CREDIT)*-1 AS MEDIA_ATRASO_DIAS, 
CREDIT_TYPE, CREDIT_ACTIVE

FROM bureau
GROUP BY CREDIT_ACTIVE, CREDIT_TYPE, CREDIT_ACTIVE
ORDER BY CONTAS_ATIVAS