SELECT DISTINCT 
SK_ID_PREV, 
MONTHS_BALANCE, 
CNT_INSTALMENT AS DURACAO_PARCELAS, 
CNT_INSTALMENT_FUTURE AS PARCELAS_PENDENTES, 
NAME_CONTRACT_STATUS, 
SK_DPD as DAYS_PAST_DUE,
SK_DPD_DEF AS DAY_PAST_DUE_TOL,
(CNT_INSTALMENT - CNT_INSTALMENT_FUTURE) AS PARCELAS_PAGAS
FROM POS_CASH_balance

