SELECT 
SK_ID_CURR,
TARGET, 
CODE_GENDER, NAME_CONTRACT_TYPE, 
FLAG_OWN_CAR, CNT_CHILDREN, 
AMT_INCOME_TOTAL, 
NAME_TYPE_SUITE, 
NAME_INCOME_TYPE, 
NAME_EDUCATION_TYPE, 
NAME_FAMILY_STATUS, 
(DAYS_BIRTH*-1)/365 as age,
OCCUPATION_TYPE,
CNT_FAM_MEMBERS, REGION_RATING_CLIENT, ORGANIZATION_TYPE
FROM application_train
