WITH tb_train as (
SELECT SK_ID_CURR,
TARGET, 
NAME_CONTRACT_TYPE, CODE_GENDER, FLAG_OWN_CAR, FLAG_OWN_REALTY,
CNT_CHILDREN, AMT_INCOME_TOTAL, AMT_CREDIT, AMT_ANNUITY,
AMT_GOODS_PRICE, NAME_TYPE_SUITE, NAME_INCOME_TYPE,
NAME_EDUCATION_TYPE, NAME_FAMILY_STATUS, NAME_HOUSING_TYPE,
REGION_POPULATION_RELATIVE,
CASE WHEN DAYS_EMPLOYED = 365243 THEN NULL
    ELSE (DAYS_EMPLOYED*-1)/365 END AS YEARS_EMPLOYED, 

(DAYS_REGISTRATION*-1) AS DAYS_REGISTRATION ,
(DAYS_ID_PUBLISH*-1) AS DAYS_ID_PUBLISH , FLAG_EMP_PHONE, FLAG_WORK_PHONE,
FLAG_CONT_MOBILE, FLAG_PHONE, FLAG_EMAIL, CNT_FAM_MEMBERS,
REGION_RATING_CLIENT, REGION_RATING_CLIENT_W_CITY,
WEEKDAY_APPR_PROCESS_START, HOUR_APPR_PROCESS_START,
REG_REGION_NOT_LIVE_REGION, REG_REGION_NOT_WORK_REGION,
LIVE_REGION_NOT_WORK_REGION, REG_CITY_NOT_LIVE_CITY,
REG_CITY_NOT_WORK_CITY, LIVE_CITY_NOT_WORK_CITY,
ORGANIZATION_TYPE, EXT_SOURCE_2, OBS_30_CNT_SOCIAL_CIRCLE,
DEF_30_CNT_SOCIAL_CIRCLE, OBS_60_CNT_SOCIAL_CIRCLE,
DEF_60_CNT_SOCIAL_CIRCLE, FLAG_DOCUMENT_3,
FLAG_DOCUMENT_4, FLAG_DOCUMENT_5, FLAG_DOCUMENT_6,
FLAG_DOCUMENT_7, FLAG_DOCUMENT_8, FLAG_DOCUMENT_9,
FLAG_DOCUMENT_10, FLAG_DOCUMENT_11, FLAG_DOCUMENT_12,
FLAG_DOCUMENT_13, FLAG_DOCUMENT_14, FLAG_DOCUMENT_15,
FLAG_DOCUMENT_16, FLAG_DOCUMENT_17, FLAG_DOCUMENT_18,
FLAG_DOCUMENT_19, FLAG_DOCUMENT_20, FLAG_DOCUMENT_21,
AMT_REQ_CREDIT_BUREAU_HOUR, AMT_REQ_CREDIT_BUREAU_DAY,
AMT_REQ_CREDIT_BUREAU_WEEK, AMT_REQ_CREDIT_BUREAU_MON,
AMT_REQ_CREDIT_BUREAU_QRT, AMT_REQ_CREDIT_BUREAU_YEAR,
(DAYS_BIRTH*-1)/365 as AGE,
(AMT_INCOME_TOTAL/AMT_CREDIT) AS INCOME_PER_CREDIT, -- FEATURES DE RENDA
(AMT_GOODS_PRICE/AMT_CREDIT) AS PRICE_PER_CREDIT, 
(AMT_ANNUITY/AMT_INCOME_TOTAL) AS ANNUITY_PER_INCOME, 
(AMT_INCOME_TOTAL)/CNT_FAM_MEMBERS AS INCOME_PER_DEPENDENTS,
ROUND(DAYS_LAST_PHONE_CHANGE*-1/365,2) AS YEARS_LAST_PHONE_CHANGE, 
(AMT_GOODS_PRICE - AMT_CREDIT) AS DIFF_PRICE,
(OWN_CAR_AGE-DAYS_EMPLOYED) AS CAR_EMPLOYED_DIFF,
-- features de contato e familia 
(FLAG_CONT_MOBILE + FLAG_MOBIL + FLAG_EMP_PHONE + FLAG_WORK_PHONE + FLAG_CONT_MOBILE + FLAG_PHONE + FLAG_EMAIL) AS FLAG_CONTACT_SUM,
(CNT_FAM_MEMBERS - CNT_CHILDREN) AS CNT_FAM_NO_CHILDREN,
(EXT_SOURCE_1 + EXT_SOURCE_2 + EXT_SOURCE_3)/3 AS MEAN_EXT

FROM application_train 
),

tb_bureau as (
SELECT 
    SK_ID_CURR,
    CREDIT_ACTIVE, 
    CREDIT_CURRENCY, 
    AMT_CREDIT_SUM_OVERDUE, 
    COALESCE(AMT_CREDIT_SUM_DEBT, 0) AS AMT_CREDIT_SUM_DEBT,
    AMT_CREDIT_SUM, 
    CREDIT_TYPE, 
    DAYS_CREDIT_ENDDATE,
    (DAYS_CREDIT_UPDATE*-1) AS DAYS_CREDIT_UPDATE,
    (DAYS_CREDIT_UPDATE*-1)/365 AS YEARS_CREDIT_UPDATE,
    (DAYS_CREDIT *-1)  AS DAYS_CREDIT,
    (DAYS_CREDIT *-1)/365 AS YEARS_CREDIT, 
CASE WHEN DAYS_CREDIT_ENDDATE IS NULL THEN NULL 
    WHEN DAYS_CREDIT_ENDDATE <0 THEN 1
    ELSE 0 END AS FLAG_ENDDATE, 
COALESCE(AMT_CREDIT_SUM_LIMIT, 0) - COALESCE(AMT_CREDIT_SUM_DEBT, 0) AS DIFF_DEBT_LIMIT,
CREDIT_DAY_OVERDUE, 
CNT_CREDIT_PROLONG,
(AMT_CREDIT_SUM_DEBT/AMT_CREDIT_SUM) AS RATE_DEBT_CREDIT, 
(AMT_CREDIT_SUM_OVERDUE/AMT_CREDIT_SUM_DEBT) AS RATE_OVERDUE_DEBT -- PODE GERAR NULOS POR DIVISAO POR 0 
FROM bureau
), 

tb_bureau_train as (
SELECT 
T1.*,
T2.*

FROM tb_train AS T1
LEFT JOIN tb_bureau AS T2
ON T1.SK_ID_CURR = T2.SK_ID_CURR
)
SELECT
    COUNT(*) AS LINHAS,
    SUM(CASE WHEN CREDIT_TYPE IS NULL THEN 1 ELSE 0 END) AS SEM_BUREAU,
    SUM(CASE WHEN CREDIT_TYPE IS NOT NULL AND DAYS_CREDIT_ENDDATE IS NULL THEN 1 ELSE 0 END) AS ENDDATE_NULO_COM_BUREAU,
    SUM(CASE WHEN CREDIT_TYPE IS NOT NULL AND AMT_CREDIT_SUM IS NULL THEN 1 ELSE 0 END) AS SUM_NULO_COM_BUREAU,
    SUM(CASE WHEN CREDIT_TYPE IS NOT NULL AND RATE_DEBT_CREDIT IS NULL THEN 1 ELSE 0 END) AS RATE_NULO_COM_BUREAU
FROM tb_bureau_train;
