SELECT 
    SK_ID_CURR,
    CREDIT_ACTIVE, 
    CREDIT_CURRENCY, 
    AMT_CREDIT_SUM_OVERDUE, 
    COALESCE(AMT_CREDIT_SUM_DEBT, 0) AS AMT_CREDIT_SUM_DEBT,
    AMT_CREDIT_SUM, 
    CREDIT_TYPE, 
    CNT_CREDIT_PROLONG, 
    DAYS_CREDIT_ENDDATE,
    (DAYS_CREDIT_UPDATE*-1) AS DAYS_CREDIT_UPDATE,
    (DAYS_CREDIT_UPDATE*-1)/365 AS YEARS_CREDIT_UPDATE,
    (DAYS_CREDIT *-1)  AS DAYS_CREDIT,
    (DAYS_CREDIT *-1)/365 AS YEARS_CREDIT, 
CASE WHEN DAYS_CREDIT_ENDDATE IS NULL THEN NULL 
    WHEN DAYS_CREDIT_ENDDATE <0 THEN 1
    ELSE 0 END AS FLAG_ENDDATE, 
COALESCE(AMT_CREDIT_SUM_LIMIT, 0) - COALESCE(AMT_CREDIT_SUM_DEBT, 0) AS DIFF_DEBT_LIMIT,
CREDIT_DAY_OVERDUE, 
CNT_CREDIT_PROLONG,
(AMT_CREDIT_SUM_DEBT/AMT_CREDIT_SUM) AS RATE_DEBT_CREDIT, 
(AMT_CREDIT_SUM_OVERDUE/AMT_CREDIT_SUM_DEBT) AS RATE_OVERDUE_DEBT -- PODE GERAR NULOS POR DIVISAO POR 0 
FROM bureau
LIMIT 10

